# Generated by Django 4.1.2 on 2022-10-31 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('dose', models.IntegerField()),
                ('concentracao', models.CharField(choices=[('mg', 'mg'), ('ml', 'ml'), ('mcg', 'mcg')], default='mg', max_length=3)),
                ('posologia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findmed.medicamento')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findmed.sintoma')),
            ],
        ),
    ]
